apiVersion: apps/v1
kind: StatefulSet
metadata:
#  namespace: default
  name: zipkin
  labels:
    app: zipkin
spec:
  serviceName: zipkin
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 450m
              memory: 1024Mi
            requests:
              cpu: 400m
              memory: 768Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            # 以下使用 elasticsearch 作为 数据存储,默认自动创建 索引 zipkin
            - name: STORAGE_TYPE
              value: elasticsearch
            - name: ES_HOSTS
              value: http://elasticsearch:9200
          ports:
            - containerPort: 9411
